#!/bin/sh

# directory of project folder

DATADIR="/home/bisp/dir/raw_data/ISICDM_2018/"
ROOTDIR="/home/bisp/dir/Pancreas_ISICDM_2020/"

# settings same as in fixed-point
LOW_RANGE=-100
HIGH_RANGE=240


MARGIN=10
# to build a uniform dimension for input of NN
#ZMAX=160
#YMAX=160
#XMAX=240
ZMAX=160
YMAX=256
XMAX=256

# parameters of training
epoch=10
init_lr=3e-4
#model_name=UNet
# ---------------- programs -------------------
cur_fold=0
#python data_preprocessing.py ${ROOTDIR} ${DATADIR} ${cur_fold} ${ZMAX} ${YMAX} ${XMAX} ${MARGIN} ${LOW_RANGE} ${HIGH_RANGE}
#python unet.py ${ROOTDIR} ${cur_fold} Trans ${epoch} ${init_lr} ${model_name}
#python unet.py ${ROOTDIR} ${cur_fold} Sagit ${epoch} ${init_lr} ${model_name}
#python unet.py ${ROOTDIR} ${cur_fold} Coron ${epoch} ${init_lr} ${model_name}

#python test_XYZ.py ${ROOTDIR} ${DATADIR} ${cur_fold} ${ZMAX} ${YMAX} ${XMAX} ${HIGH_RANGE} ${LOW_RANGE} ${MARGIN} ${model_name}
#