clc;clear;
clear all;
close all;
genPPT=0;

for k=1:1:16
    p=k;
    filename=[num2str(p) '.mat']
    %filename=sprintf('%04d.mat',p)

    load(['H:\ISICDM_Mat\ISICDM_test_mat\GS\y_' filename]);GS=double(y);
    load(['H:\ISICDM_Mat\ISICDM_test_mat\Img\X_' filename]); Img=double(X);
    load(['H:\ISICDM_Mat\ISICDM_test_mat\Pred_2D\y_pred_' filename]); SEG_2D=double(pred);
    load(['H:\ISICDM_Mat\ISICDM_test_mat\Pred_3D\y_pred_' filename]); SEG_3D=double(pred3D);
    GS(GS==255)=1;
    SEG_3D(SEG_3D==255)=1;
    
    D3D(k,1)=Dice_Ratio(SEG_3D,GS);
    SEG_2D = Label_connected(SEG_2D);
    D2D(k,1)=Dice_Ratio(SEG_2D,GS)
    
end

%% 
if genPPT==1
    Bsize=2;
    Img = Img_to_show(Img);
    isOpen  = exportToPPTX();

    if ~isempty(isOpen)
        % If PowerPoint already started, then close first and then open a new one
        exportToPPTX('close');
    end

    exportToPPTX('new','Dimensions',[12 6], ...
        'Title','Seg_results', ...
        'Author','Yue', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');

    % Additionally background color for all slides can be set as follows:
    % exportToPPTX('new','BackgroundColor',[0.5 0.5 0.5]);
    fileStats   = exportToPPTX('query');

    if ~isempty(fileStats)
        fprintf('Presentation size: %f x %f\n',fileStats.dimensions);
        fprintf('Number of slides: %d\n',fileStats.numSlides);
    end

    newFile = exportToPPTX('saveandclose','Seg_results');
    exportToPPTX('open','Seg_results');

    for slice_num=1:1:size(GS,3)
        slideId  = exportToPPTX('addslide');
        Img_= squeeze(Img(:,:,slice_num));
        GS_= squeeze(GS(:,:,slice_num));
        Img_3 = Img_GS_to_Img3(Img_,GS_,1);
        SEG_2D_= squeeze(SEG_2D(:,:,slice_num));
        SEG_3D_= squeeze(SEG_3D(:,:,slice_num));

        SEG_2D_3=DSC_imshow(GS_,SEG_2D_>0.5);
        SEG_3D_3=DSC_imshow(GS_,SEG_3D_>0.5);  

    %% 

        exportToPPTX('addpicture',Img_,'Position',[0 0 Bsize Bsize])
        exportToPPTX('addpicture',GS_,'Position',[Bsize 0 Bsize Bsize])
        exportToPPTX('addpicture',SEG_3D_,'Position',[2*Bsize 0 Bsize Bsize])
        exportToPPTX('addpicture',SEG_2D_,'Position',[3*Bsize 0 Bsize Bsize])

        exportToPPTX('addpicture',Img_3 ,'Position',[Bsize Bsize Bsize Bsize])
        exportToPPTX('addpicture',SEG_3D_3,'Position',[2*Bsize Bsize Bsize Bsize])
        exportToPPTX('addpicture',SEG_2D_3,'Position',[3*Bsize Bsize Bsize Bsize])


        for i=1:1:5
            for j=1:1:2
                exportToPPTX('addtext','','Position',[(i-1)*Bsize (j-1)*Bsize Bsize Bsize],'LineWidth',2,'EdgeColor',[1,1,1]);
            end
        end
    end
    exportToPPTX('saveandclose');
    
else
end

